services:
  jupyter:
    image: jupyter-langs:latest
    container_name: jupyter-manylang
    hostname: jupyter
    command:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--port=7654",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/notebooks",
        "--config=/config/jupyter_notebook_config.py",
      ]
    ports:
      - "7654:7654"
    volumes:
      - ./notebooks:/notebooks
      - ./config:/config
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - GRANT_SUDO=no
      - RESTARTABLE=yes
      - JUPYTER_CONFIG_DIR=/config
      - NOTEBOOK_DIR=/notebooks
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7654/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
