version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOLANG_VERSION=1.21.5
        - JULIA_VERSION=1.10.0
        - RUST_VERSION=1.75.0
        - NODE_VERSION=20.10.0
    image: jupyter-multilang:latest
    container_name: jupyter-multilang
    hostname: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./config:/config
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - GRANT_SUDO=no
      - RESTARTABLE=yes
      - JUPYTER_CONFIG_DIR=/config
      - NOTEBOOK_DIR=/notebooks
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
